# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: calc.proto for package 'example'
# Original file comments:
# protoファイルの記述に使用する文法を指定

require 'grpc'
require_relative 'calc_pb'

module Example
  module Calc
    # 計算機のサービスを定義
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'example.Calc'

      # Inputを引数に渡すとOutputを返すsolveというメソッドを定義
      rpc :Solve, ::Example::Input, ::Example::Output
    end

    Stub = Service.rpc_stub_class
  end
end
